package edu.learning.spring.model;

// Generated Feb 24, 2014 7:30:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private UserProfileId id;

	public UserProfile() {
	}

	public UserProfile(UserProfileId id) {
		this.id = id;
	}

	public UserProfileId getId() {
		return this.id;
	}

	public void setId(UserProfileId id) {
		this.id = id;
	}

}
